version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    depends_on:
        - sqldata
  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        - SA_PASSWORD=FiapAlura&TechChallenge1
        - ACCEPT_EULA=Y
    volumes:
        - c:\dados\volumes\mssql:/var/opt/mssql/data
    ports:
        - "1433:1433"
